# This is a basic workflow to help you get started with Actions

name: Build docker container

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Get maven version
        id: project-version
        uses: jactions/maven-version@v1.1.0
      - name: Build the project
        run: |
          mvn -B package --file pom.xml
          echo Build completed
      - name: Logging in to GICR
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build . --tag ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest --tag ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:${{ steps.project-version.outputs.version }}
      - name: Publish docker container
        run: |
          docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }} --all-tags
          echo Published docker container
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Running the docker container
        run: docker run ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
      
