# This is a basic workflow to help you get started with Actions

name: Build docker container

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Build the project
        run: |
          mvn -B package --file pom.xml
          echo Build completed
      - name: Logging in to GICR
        run: echo ${{ github.token }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build Docker image
        run: docker build . --tag ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
      - name: Publish docker container
        run: |
          docker run ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
          echo Published docker container
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Running the docker container
        run: docker run ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}:latest
      
